"""Jetson GPU / CUDA / TensorRT diagnostics.

Run this ON the Jetson to find out what acceleration is actually available:

    python3 tools/jetson_diagnostics.py

It probes the board model, the OpenCV build (CUDA support, tracking module),
the CUDA device count and whether TensorRT/pyCUDA import, then writes a markdown
report to ``docs/JETSON_DIAGNOSTICS.md``. It makes no claims it cannot verify --
in particular OpenCV's CSRT/KCF run on the CPU; there is no CUDA implementation
of those trackers, so a CUDA device does NOT make CSRT GPU-accelerated.
"""

from __future__ import annotations

import platform
import sys
from pathlib import Path


def read_board_model() -> str:
    model_path = Path("/proc/device-tree/model")
    try:
        return model_path.read_text(errors="replace").strip("\x00").strip()
    except OSError:
        return "unknown (not a Jetson / file unavailable)"


def probe_opencv() -> dict:
    info: dict = {}
    try:
        import cv2
    except ImportError as exc:
        info["available"] = False
        info["error"] = str(exc)
        return info

    info["available"] = True
    info["version"] = cv2.__version__
    try:
        info["cuda_devices"] = int(cv2.cuda.getCudaEnabledDeviceCount())
    except Exception as exc:  # noqa: BLE001 - report, never hide
        info["cuda_devices"] = 0
        info["cuda_error"] = str(exc)

    build = cv2.getBuildInformation()
    info["build_cuda_yes"] = "CUDA:                          YES" in build or "NVIDIA CUDA" in build
    legacy = getattr(cv2, "legacy", None)
    info["has_csrt"] = hasattr(cv2, "TrackerCSRT_create") or bool(
        legacy and hasattr(legacy, "TrackerCSRT_create")
    )
    info["has_kcf"] = hasattr(cv2, "TrackerKCF_create") or bool(
        legacy and hasattr(legacy, "TrackerKCF_create")
    )
    return info


def probe_module(name: str) -> dict:
    try:
        module = __import__(name)
    except ImportError as exc:
        return {"available": False, "error": str(exc)}
    return {"available": True, "version": getattr(module, "__version__", "unknown")}


def gather() -> dict:
    return {
        "board_model": read_board_model(),
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "opencv": probe_opencv(),
        "tensorrt": probe_module("tensorrt"),
        "pycuda": probe_module("pycuda"),
    }


def render_markdown(data: dict) -> str:
    cv = data["opencv"]
    trt = data["tensorrt"]
    lines = [
        "# Jetson diagnostics (generated)",
        "",
        "> Generated by `tools/jetson_diagnostics.py`. Re-run on the target board.",
        "",
        "## Platform",
        f"- Board model: `{data['board_model']}`",
        f"- Python: {data['python']}",
        f"- Platform: {data['platform']}",
        "",
        "## OpenCV",
    ]
    if not cv.get("available"):
        lines.append(f"- OpenCV not importable: {cv.get('error')}")
    else:
        lines += [
            f"- Version: {cv.get('version')}",
            f"- Built with CUDA: {'yes' if cv.get('build_cuda_yes') else 'no'}",
            f"- CUDA-enabled devices: {cv.get('cuda_devices', 0)}",
            f"- CSRT available: {cv.get('has_csrt')}",
            f"- KCF available: {cv.get('has_kcf')}",
        ]
    lines += [
        "",
        "## TensorRT / CUDA runtime",
        f"- TensorRT: {'yes, ' + trt.get('version', '') if trt.get('available') else 'not installed'}",
        f"- pyCUDA: {'yes' if data['pycuda'].get('available') else 'not installed'}",
        "",
        "## Notes",
        "- OpenCV CSRT/KCF trackers are CPU-only; a CUDA device does not "
        "accelerate them.",
        "- If `Built with CUDA` is yes and devices > 0, only offload measured "
        "hotspots (e.g. `resize`/preprocessing via `cv2.cuda`).",
        "- Do not add heavy GPU dependencies without a measured speed-up "
        "(compare with `python3 main.py --benchmark`).",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    data = gather()
    report = render_markdown(data)
    out_path = Path(__file__).resolve().parent.parent / "docs" / "JETSON_DIAGNOSTICS.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(report)
    print(f"Written to {out_path}")


if __name__ == "__main__":
    main()
